[build]
builder = "RAILPACK"
buildCommand = "npm run build"
watchPatterns = [
  "package.json",
  ".yarnrc.yml",
  ".yarn/releases/**",
  "frontend/**"
]

[deploy]
startCommand = "npm run start"
restartPolicyType = "ALWAYS"
healthcheckPath = "/"
