$schema = "https://railway.com/railway.schema.json"

[build]
builder = "RAILPACK"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
restartPolicyType = "ALWAYS"
