$schema = "https://railway.com/railway.schema.json"

[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port ${PORT}"
healthcheckPath = "/health"
restartPolicyType = "ALWAYS"
