[build]
builder = "DOCKERFILE"
watchPatterns = [
  "data-pipeline/**"
]

[deploy]
restartPolicyType = "ON_FAILURE"
startCommand = "bash -lc \"python3 wait_for_db.py && PIPELINE_SINGLE_STAGE=1 python3 -u update_pipeline.py && PIPELINE_SINGLE_STAGE=1 python3 -u update_fjord_data.py\""
cronSchedule = "0 6 * * *"
