[build]
builder = "DOCKERFILE"
watchPatterns = [
  "data-pipeline/**"
]

[deploy]
restartPolicyType = "ON_FAILURE"
startCommand = "bash -lc \"python3 wait_for_db.py && python3 -u update_pipeline.py && python3 -u update_fjord_data.py\""
cronSchedule = "0 3 * * *"
