$schema = "https://railway.com/railway.schema.json"

[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "bash -lc \"python3 wait_for_db.py && python3 -u update_pipeline.py && python3 -u update_fjord_data.py\""
restartPolicyType = "ON_FAILURE"
cronSchedule = "0 3 * * *"
