/**
 * Generated by scripts/gen-image-meta.mjs. Do not edit by hand.
 *
 * Intrinsic pixel dimensions of everything in public/images, so next/image can
 * reserve the right box for a photo whose src is only known at runtime.
 */
export interface ImageSize {
  width: number;
  height: number;
}

export const IMAGE_META: Record<string, ImageSize> = {
  "/images/community-bonds.jpg": { width: 1286, height: 1500 },
  "/images/dogs.jpg": { width: 1211, height: 1500 },
  "/images/heartofaseal-28.jpg": { width: 2800, height: 2249 },
  "/images/heartofaseal_fisherboat.jpg": { width: 1000, height: 1500 },
  "/images/heartofaseal_fishing.jpg": { width: 2800, height: 1866 },
  "/images/heartofaseal_iceberg.jpg": { width: 1214, height: 1500 },
  "/images/heartofaseal_town.jpg": { width: 2800, height: 1867 },
  "/images/heartofaseal_voices.jpg": { width: 2500, height: 1667 },
  "/images/heartofaseal_website11.jpg": { width: 3000, height: 2000 },
  "/images/heartofaseal_wind.jpg": { width: 1198, height: 1500 },
  "/images/kids_drumdance.jpg": { width: 1000, height: 1500 },
  "/images/knud.jpg": { width: 500, height: 647 },
  "/images/motorsledge.jpg": { width: 2000, height: 1333 },
  "/images/og-cover.jpg": { width: 1200, height: 630 },
  "/images/overlay.jpg": { width: 1251, height: 1500 },
  "/images/pipeline.png": { width: 1688, height: 950 },
  "/images/satellite.jpg": { width: 1251, height: 1500 },
};

/**
 * Falls back to a 3:2 landscape box. A missing entry means someone added a
 * photo without regenerating this file; the layout stays sane and the photo
 * still renders, it just loses its exact aspect ratio until the script is run.
 */
export const imageSize = (src: string): ImageSize =>
  IMAGE_META[src] ?? { width: 1500, height: 1000 };
