/**
 * Generated by scripts/gen-photo-variants.mjs. Do not edit by hand.
 *
 * Which pre-encoded widths exist for each photograph, and its intrinsic size.
 * The files themselves are in public/photos, named <stem>-<width>.<format>.
 *
 * lib/__tests__/photoVariants.test.ts checks that this file, the files on disk
 * and the photographs the story actually references still agree.
 */
export interface PhotoVariant {
  /** File name without extension, which is also the variant file name stem. */
  stem: string;
  width: number;
  height: number;
  /** Ascending. The last one is the photograph's own resolution. */
  widths: number[];
}

export const PHOTO_VARIANTS: Record<string, PhotoVariant> = {
  "/images/community-bonds.jpg": { stem: "community-bonds", width: 1286, height: 1500, widths: [640, 828, 1286] },
  "/images/dogs.jpg": { stem: "dogs", width: 1211, height: 1500, widths: [640, 828, 1211] },
  "/images/heartofaseal-28.jpg": { stem: "heartofaseal-28", width: 2800, height: 2249, widths: [640, 828, 1200, 1920, 2800] },
  "/images/heartofaseal_fisherboat.jpg": { stem: "heartofaseal_fisherboat", width: 1000, height: 1500, widths: [640, 828, 1000] },
  "/images/heartofaseal_fishing.jpg": { stem: "heartofaseal_fishing", width: 2800, height: 1866, widths: [640, 828, 1200, 1920, 2800] },
  "/images/heartofaseal_iceberg.jpg": { stem: "heartofaseal_iceberg", width: 1214, height: 1500, widths: [640, 828, 1214] },
  "/images/heartofaseal_town.jpg": { stem: "heartofaseal_town", width: 2800, height: 1867, widths: [640, 828, 1200, 1920, 2800] },
  "/images/heartofaseal_voices.jpg": { stem: "heartofaseal_voices", width: 2500, height: 1667, widths: [640, 828, 1200, 1920, 2500] },
  "/images/heartofaseal_website11.jpg": { stem: "heartofaseal_website11", width: 3000, height: 2000, widths: [640, 828, 1200, 1920, 2560, 3000] },
  "/images/heartofaseal_wind.jpg": { stem: "heartofaseal_wind", width: 1198, height: 1500, widths: [640, 828, 1198] },
  "/images/kids_drumdance.jpg": { stem: "kids_drumdance", width: 1000, height: 1500, widths: [640, 828, 1000] },
  "/images/knud.jpg": { stem: "knud", width: 500, height: 647, widths: [500] },
  "/images/motorsledge.jpg": { stem: "motorsledge", width: 2000, height: 1333, widths: [640, 828, 1200, 2000] },
  "/images/pipeline.png": { stem: "pipeline", width: 1688, height: 950, widths: [640, 828, 1200, 1688] },
};
