name: Update Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Data Update Script
        run: |
          cd backend
          python update_data.py

      - name: Commit and Push Updated Data
        run: |
          git config --global user.email "lukas.kreibig@posteo.de"
          git config --global user.name "Lukas Kreibig"
          git add backend/data/data.json
          git commit -m "Daily data update: $(date)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
